---
- name: "Include vars into the venafi variable from {{ credentials_file }} "
  ansible.builtin.include_vars:
    file: "{{ credentials_file }}"
    name: venafi

- name: "Show execution mode"
  ansible.builtin.debug:
    msg: "ssh_ca_remote_execution is {{ ssh_ca_remote_execution }}"

- name: "Local CA"
  ansible.builtin.import_tasks: local-ca.yml
  when: not ssh_ca_remote_execution

- name: "Remote CA"
  ansible.builtin.import_tasks: remote-ca.yml
  when: ssh_ca_remote_execution
