---
credentials_file: credentials.yml

# Use Ansible host FQDN for certificate common name
ssh_key_id: "{{ ansible_fqdn }}"
# Directory where to place certificates
ssh_cert_dir: "/etc/ssh/{{ ssh_key_id }}"
# Paths for certificate and keys
ssh_cert_path: "{{ ssh_cert_dir }}/{{ ssh_key_id }}-cert.pub"
ssh_public_key_path: "{{ ssh_cert_dir }}/{{ ssh_key_id }}.pub"
ssh_private_key_path: "{{ ssh_cert_dir }}/{{ ssh_key_id }}"

# Where to execute venafi_certificate module. If set to false, certificate will be
# created on ansible master host and then copied to the remote server
ssh_remote_execution: false
# Remote location where to place the certificate
ssh_remote_cert_path: "{{ ssh_cert_dir }}/{{ ssh_key_id }}-cert.pub"
ssh_remote_public_key_path: "{{ ssh_cert_dir }}/{{ ssh_key_id }}.pub"
ssh_remote_private_key_path: "{{ ssh_cert_dir }}/{{ ssh_key_id }}"
# Set to false, if you don't want to copy private/public key to remote location
ssh_copy_private_key_to_remote: true
ssh_copy_public_key_to_remote: true
