---
- name: "Include vars into the venafi variable from {{ credentials_file }}"
  ansible.builtin.include_vars:
    file: "{{ credentials_file }}"
    name: venafi

- name: "Show execution mode"
  ansible.builtin.debug:
    msg: "ssh_remote_execution is {{ ssh_remote_execution }}"

- name: "Local SSH Certificate"
  ansible.builtin.import_tasks: local-certificate.yml
  when: not ssh_remote_execution

- name: "Remote SSH Certificate"
  ansible.builtin.import_tasks: remote-certificate.yml
  when: ssh_remote_execution
