# Generates certificate on remote host
---
- name: "Enroll Venafi SSH certificate on local host"
  venafi.machine_identity.venafi_ssh_certificate:
    url: "{{ venafi.url | default(omit) }}"
    test_mode: "{{ venafi.test_mode if venafi.test_mode is defined else 'false' }}"
    user: "{{ venafi.user | default(omit) }}"
    password: "{{ venafi.password | default(omit) }}"
    access_token: "{{ venafi.access_token | default(omit) }}"
    trust_bundle: "{{ venafi.trust_bundle  | default(omit) }}"
    cert_path: "{{ certificate_cert_path }}"
    public_key_path: "{{ certificate_public_key_path }}"
    private_key_path: "{{ certificate_private_key_path }}"
    cadn: "{{ certificate_cadn }}"
    key_id: "{{ certificate_key_id }}"
    ssh_key_generation_type: "{{ certificate_ssh_key_generation_type | default(omit) }}"
    private_key_passphrase: "{{ certificate_private_key_passphrase | default(omit) }}"
    ssh_key_size: "{{ certificate_ssh_key_size | default(omit) }}"
    validity_period: "{{ certificate_validity_period | default(omit) }}"
    policy_dn: "{{ certificate_policy_dn | default(omit) }}"
    object_name: "{{ certificate_object_name | default(omit) }}"
    destination_addresses: "{{ certificate_destination_addresses | default(omit) }}"
    principals: "{{ certificate_principals | default(omit) }}"
    extensions: "{{ certificate_extensions | default(omit) }}"
    force_command: "{{ certificate_force_command | default(omit) }}"
    source_addresses: "{{ certificate_source_addresses | default(omit) }}"
    windows_cert: "{{ certificate_windows_cert | default(omit) }}"
    force: "{{ certificate_force if certificate_force is defined else false }}"
  delegate_to: localhost
  register: certout
- name: "dump test output"
  debug:
    msg: "{{ certout }}"
