name: ansible-test sanity
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * *'

jobs:
  sanity:
    timeout-minutes: 30
    name: Ansible Sanity (Ⓐ${{ matrix.ansible }}) tests
    strategy:
      matrix:
        ansible:
        - stable-2.14
        - stable-2.15
        # - devel
    runs-on: ubuntu-latest
    steps:
      - name: Perform testing
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: ${{ matrix.ansible }}
          # pre-test-cmd:
          python-version: 3.9
          target-python-version: 3.9
          testing-type: sanity
          # test-deps:
